### ISSUE TITLE
Migrate from CloudFormation Output to Lambda Variables

### ISSUE THREAD

**Issue by hxrsmurf** [hxrsmurf/spotify#21]
I previously referenced the SSM Parameter names in CloudFormation Output. Then, scanned and parsed the CFT Output. 

I can simply reference these SSM Parameters within Lambda variable:

Working example below:

```
Resources:
  Lambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.9
      CodeUri: python
      Timeout: 15
      Environment:
        Variables:
          PreviousEntryEpochTime: !Ref ParameterPreviousEntryEpochTime
```
